title: Recommandé
url: https://recommande.duckdns.org

### download_url: is needed, if and only if audio files are hosted in a different location, it is the path of the directory where the audio files are stored
download_url: "https://dts.podtrac.com/redirect.mp3/shelter.mahoro-net.org/~yattoz/recommande/episodes"
subtitle: Le podcast musical par vidéos recommandées. 
description: En partant d'une musique choisie de préférence parmi les propositions d'auditeurs, on saute de musique recommandée en musique recommandée. Cohérence facultative.
author: Yattoz

### author_url: This is the URL of a site owned by the author (see https://jsonfeed.org/version/1)
author_url: "https://recommande.duckdns.org"

email: recommande@hotmail.com
keywords: [octopod, podcast, music, musique, youtube, recommandé]
itunes_categories: [Music]
episodes_per_feed_page: 100

player_theme: default-dark # default | "default-dark" | legacy | minimal | republica

### Date can be localized via date_de.rb plugin, you don't need to change this
date_format: ordinal

### Rsync Deploy config: Be sure your public key is listed in your server's ~/.ssh/authorized_keys file
ssh_host: user@host.org
ssh_port: 22
document_root: /path/to/your/htdocs/
rsync_delete: true

### Twiter config, optional
twitter_nick: yattoz # Twitter will not be used unless this is set

language: fr
explicit: "no" # "yes" | "no" | clean

### License Config, you really should configure this
license: CC BY NC SA 4.0
license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
license_image_url: https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png

### Feed links, optional
itunes_url: https://itunes.apple.com/at/podcast/myname/id232323
# bitlove_url: https://bitlove.org/myaccount
# fyyd_url: https://fyyd.de/podcast/myaccount/myid
# gpodder_url: https://gpodder.net/podcast/mypodcast

### Additional Feeds, optional
#  itunes: http://itunes.apple.com/de/podcast/podcast_name/id42424242
#  torrent_m4a: http://bitlove.org/example_user/example_podcast_m4a/feed
#  torrent_mp3: http://bitlove.org/example_user/example_podcast_mp3/feed

### Flattr config, optional
flattr_uid: # Flattr will not be used unless this is set
flattr_button: compact # compact | default
flattr_mode: auto # auto | manual
flattr_popout:  1 # 1 | 0 (show popout when hovering mouse over button)
flattr_language: fr_FR # available languages see https://api.flattr.com/rest/v2/languages.txt
flattr_category: audio # available categories see https://api.flattr.com/rest/v2/categories.txt

### Disqus comments
disqus_shortname: yattoz-recommande # Disqus will not be used unless this is set
disqus_developer: 0 # 1 | 0
comments: true

### Isso comments
use_isso: "yes" # "no" | "yes"

theme: jekyll-bootflat

### Jekyll Admin: uncomment the last line of this paragraph to enable Jekyll Admin.
### (but you will loose auto regeneration after code changes with a text editor then)
plugins:
  - jekyll-octopod
#  - jekyll-admin
